### ISSUE TITLE
panorama broken since 729b946

### ISSUE THREAD

**Issue by gangelop** [Psycojoker/prosopopee#121]
panorama broken since 729b946

Currently in master at 0c6e83f build exits successfully but render fails in browser with console output:
```js
jquery.min.js:2 Uncaught TypeError: e.indexOf is not a function
    at k.fn.init.k.fn.load (jquery.min.js:2)
    at HTMLElement.<anonymous> (jquery.panorama_viewer.min.js:1)
    at Function.each (jquery.min.js:2)
    at k.fn.init.each (jquery.min.js:2)
    at k.fn.init.e.fn.panorama_viewer (jquery.panorama_viewer.min.js:1)
    at (index):82
k.fn.load @ jquery.min.js:2
(anonymous) @ jquery.panorama_viewer.min.js:1
each @ jquery.min.js:2
each @ jquery.min.js:2
e.fn.panorama_viewer @ jquery.panorama_viewer.min.js:1
(anonymous) @ (index):82

```
Might investigate further but I've never touched jQuery before.

**Comment by QSchulz** [comment]
See: https://github.com/peachananr/panorama_viewer/issues/19#issuecomment-517641936 for how to fix this issue.

Considering this JS script hasn't seen any code update in the last 6 years and a half, maybe it'd be time to actually swap to something more recent?
